		$("#zhua").hover(function(){
			$(this).find(".fix").stop().slideToggle(500);
		})
		$(".An").hover(function(){
			$(".lia").css("display","block")
		},function(){
			$(".lia").css("display","none")
		})
		$(".Bn").hover(function(){
			$(".lib").css("display","block")
		},function(){
			$(".lib").css("display","none")
		})
		$(".Cn").hover(function(){
			$(".lic").css("display","block")
		},function(){
			$(".lic").css("display","none")
		})	
		$(".Dn").hover(function(){
			$(".lid").css("display","block")
		},function(){
			$(".lid").css("display","none")
		})	
		$(".En").hover(function(){
			$(".lie").css("display","block")
		},function(){
			$(".lie").css("display","none")
		})	
		$(".Fn").hover(function(){
			$(".lif").css("display","block")
		},function(){
			$(".lif").css("display","none")
		})		
		$(".Gn").hover(function(){
			$(".lig").css("display","block")
		},function(){
			$(".lig").css("display","none")
		})			
		$(".Hn").hover(function(){
			$(".lih").css("display","block")
		},function(){
			$(".lih").css("display","none")
		})			
		$(".In").hover(function(){
			$(".lii").css("display","block")
		},function(){
			$(".lii").css("display","none")
		})	
		$(".Jn").hover(function(){
			$(".lij").css("display","block")
		},function(){
			$(".lij").css("display","none")
		})			
